// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-tasks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase-for-user.ts
import { createClient } from "npm:@supabase/supabase-js@2.112.4";
function supabaseForUser(ctx) {
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  const accessToken = ctx.getToken();
  if (!supabaseUrl || !supabaseKey || !accessToken) {
    throw new Error("MCP backend authentication is not configured correctly");
  }
  return createClient(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${accessToken}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-tasks.ts
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's tasks (studies/assignments), optionally filtered by status and whether archived.",
  inputSchema: {
    status: z.string().optional().describe("Optional status filter, e.g. the exact status name of a task."),
    include_archived: z.boolean().optional().describe("Include archived tasks. Defaults to false."),
    limit: z.number().int().min(1).max(100).optional().describe("Max number of tasks to return. Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, include_archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("tasks").select("id, subject_name, description, due_date, status, is_group_work, is_archived, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (!include_archived) query = query.eq("is_archived", false);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a new task (study/assignment) for the signed-in user via the app's database.",
  inputSchema: {
    subject_name: z2.string().trim().min(1).describe("Subject or title of the task."),
    description: z2.string().trim().optional().describe("Optional details about the task."),
    due_date: z2.string().optional().describe("Optional due date in YYYY-MM-DD format."),
    status: z2.string().optional().describe("Optional status name. Defaults to the app's default status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ subject_name, description, due_date, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const insert = {
      user_id: ctx.getUserId(),
      subject_name
    };
    if (description) insert.description = description;
    if (due_date) insert.due_date = due_date;
    if (status) insert.status = status;
    const { data, error } = await supabaseForUser(ctx).from("tasks").insert(insert).select("id, subject_name, status, due_date").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/list-study-cycles.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_study_cycles_default = defineTool3({
  name: "list_study_cycles",
  title: "List study cycles",
  description: "List the signed-in user's study cycles with their blocks (subjects and allocated minutes).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("study_cycles").select(
      "id, name, is_active, start_date, end_date, study_cycle_blocks(allocated_minutes, order_index, subjects(name))"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { cycles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool4({
  name: "get_leaderboard",
  title: "Get ranking",
  description: "Get the XP leaderboard (ranking) of users for a given period. Returns top users ordered by total XP.",
  inputSchema: {
    period: z3.enum(["daily", "weekly", "monthly", "all_time"]).optional().describe("Ranking period. Defaults to 'weekly'."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max number of entries to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ period, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).rpc("get_leaderboard", {
      period_type: period ?? "weekly"
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = (data ?? []).slice(0, limit ?? 20);
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { leaderboard: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vxsahhwkgnynxwpjsxaj";
var mcp_default = defineMcp({
  name: "zenit-mcp",
  title: "Zenit MCP",
  version: "0.1.0",
  instructions: "Tools for Zenit, a study, focus and productivity app. Use `list_tasks` and `create_task` to manage the signed-in user's tasks, `list_study_cycles` to inspect their study cycles, and `get_leaderboard` to read the XP ranking.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tasks_default, create_task_default, list_study_cycles_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
